version: '3.8'

services:
  frontend:
    image: sujeong9928/fixlog-front:latest
    container_name: fixlog-frontend
    ports:
      - "3000:3000"
    command: yarn start
    restart: always
    environment:
      - NODE_ENV=production
    env_file:
      - .env.production
