export interface dummyFeedItems {
  id: number;
  author: string;
  profileImage: string;
  follow: boolean;
  title: string;
  content: string;
  date: string;
  time: string;
  likes: number;
  comments: number;
}

export const dummyFeedPosts = [
  {
    id: 1,
    author: '개발자작냐고',
    profileImage: '/avatar2.png',
    follow: true,
    title: '오늘의 주제: "프론트엔드 언어의 역사"',
    content: `너 진짜 프론트엔드 할 거야? 그게 진짜 까다롭구 어려워 생각보다 아니 그니까 일단 눈에 보이는 거라서 어쩌면 더 어려울 수 있다니까는? 눈에 보이기만 하면 뭐하냐고 예뻐보여야하는데... 이런 거면 디자이너랑 뭐가 다른데 진짜 돈 더 줘라 돈 더 줘! 프론트 연봉 올려줘라 줘!!!!. `,
    date: '2025.06.13',
    time: '3시간 전',
    likes: 258,
    comments: 18,
  },
  {
    id: 2,
    author: '개발자작냐고',
    profileImage: '/avatar2.png',
    follow: true,
    title: '오늘의 주제: "프론트엔드 언어의 역사"',
    content: `너 진짜 프론트엔드 할 거야? 그게 진짜 까다롭구 어려워 생각보다 아니 그니까 일단 눈에 보이는 거라서 어쩌면 더 어려울 수 있다니까는? 눈에 보이기만 하면 뭐하냐고 예뻐보여야하는데... 이런 거면 디자이너랑 뭐가 다른데 진짜 돈 더 줘라 돈 더 줘! 프론트 연봉 올려줘라 줘!!!!`,
    date: '2025.06.13',
    time: '3시간 전',
    likes: 258,
    comments: 18,
  },
  {
    id: 3,
    author: '개발자작냐고',
    profileImage: '/avatar2.png',
    follow: false,
    title: '오늘의 주제: "프론트엔드 언어의 역사"',
    content: `너 진짜 프론트엔드 할 거야? 그게 진짜 까다롭구 어려워 생각보다 아니 그니까 일단 눈에 보이는 거라서 어쩌면 더 어려울 수 있다니까는? 눈에 보이기만 하면 뭐하냐고 예뻐보여야하는데... 이런 거면 디자이너랑 뭐가 다른데 진짜 돈 더 줘라 돈 더 줘! 프론트 연봉 올려줘라 줘!!!!`,
    date: '2025.06.13',
    time: '3시간 전',
    likes: 258,
    comments: 18,
  },
  {
    id: 4,
    author: '개발자작냐고',
    profileImage: '/avatar2.png',
    follow: true,
    title: '오늘의 주제: "프론트엔드 언어의 역사"',
    content: `너 진짜 프론트엔드 할 거야? 그게 진짜 까다롭구 어려워 생각보다 아니 그니까 일단 눈에 보이는 거라서 어쩌면 더 어려울 수 있다니까는? 눈에 보이기만 하면 뭐하냐고 예뻐보여야하는데... 이런 거면 디자이너랑 뭐가 다른데 진짜 돈 더 줘라 돈 더 줘! 프론트 연봉 올려줘라 줘!!!!`,
    date: '2025.06.13',
    time: '3시간 전',
    likes: 258,
    comments: 18,
  },
  {
    id: 5,
    author: '개발자작냐고',
    profileImage: '/avatar2.png',
    follow: false,
    title: '오늘의 주제: "프론트엔드 언어의 역사"',
    content: `너 진짜 프론트엔드 할 거야? 그게 진짜 까다롭구 어려워 생각보다 아니 그니까 일단 눈에 보이는 거라서 어쩌면 더 어려울 수 있다니까는? 눈에 보이기만 하면 뭐하냐고 예뻐보여야하는데... 이런 거면 디자이너랑 뭐가 다른데 진짜 돈 더 줘라 돈 더 줘! 프론트 연봉 올려줘라 줘!!!!`,
    date: '2025.06.13',
    time: '3시간 전',
    likes: 258,
    comments: 18,
  },
  {
    id: 6,
    author: '개발자작냐고',
    profileImage: '/avatar2.png',
    follow: true,
    title: '오늘의 주제: "프론트엔드 언어의 역사"',
    content: `너 진짜 프론트엔드 할 거야? 그게 진짜 까다롭구 어려워 생각보다 아니 그니까 일단 눈에 보이는 거라서 어쩌면 더 어려울 수 있다니까는? 눈에 보이기만 하면 뭐하냐고 예뻐보여야하는데... 이런 거면 디자이너랑 뭐가 다른데 진짜 돈 더 줘라 돈 더 줘! 프론트 연봉 올려줘라 줘!!!!`,
    date: '2025.06.13',
    time: '3시간 전',
    likes: 258,
    comments: 18,
  },
  {
    id: 7,
    author: '개발자작냐고',
    profileImage: '/avatar2.png',
    follow: false,
    title: '오늘의 주제: "프론트엔드 언어의 역사"',
    content: `너 진짜 프론트엔드 할 거야? 그게 진짜 까다롭구 어려워 생각보다 아니 그니까 일단 눈에 보이는 거라서 어쩌면 더 어려울 수 있다니까는? 눈에 보이기만 하면 뭐하냐고 예뻐보여야하는데... 이런 거면 디자이너랑 뭐가 다른데 진짜 돈 더 줘라 돈 더 줘! 프론트 연봉 올려줘라 줘!!!!`,
    date: '2025.06.13',
    time: '3시간 전',
    likes: 258,
    comments: 18,
  },
  {
    id: 8,
    author: '개발자작냐고',
    profileImage: '/avatar2.png',
    follow: true,
    title: '오늘의 주제: "프론트엔드 언어의 역사"',
    content: `너 진짜 프론트엔드 할 거야? 그게 진짜 까다롭구 어려워 생각보다 아니 그니까 일단 눈에 보이는 거라서 어쩌면 더 어려울 수 있다니까는? 눈에 보이기만 하면 뭐하냐고 예뻐보여야하는데... 이런 거면 디자이너랑 뭐가 다른데 진짜 돈 더 줘라 돈 더 줘! 프론트 연봉 올려줘라 줘!!!!`,
    date: '2025.06.13',
    time: '3시간 전',
    likes: 258,
    comments: 18,
  },
  {
    id: 9,
    author: '개발자작냐고',
    profileImage: '/avatar2.png',
    follow: false,
    title: '오늘의 주제: "프론트엔드 언어의 역사"',
    content: `너 진짜 프론트엔드 할 거야? 그게 진짜 까다롭구 어려워 생각보다 아니 그니까 일단 눈에 보이는 거라서 어쩌면 더 어려울 수 있다니까는? 눈에 보이기만 하면 뭐하냐고 예뻐보여야하는데... 이런 거면 디자이너랑 뭐가 다른데 진짜 돈 더 줘라 돈 더 줘! 프론트 연봉 올려줘라 줘!!!!`,
    date: '2025.06.13',
    time: '3시간 전',
    likes: 258,
    comments: 18,
  },
  {
    id: 10,
    author: '개발자작냐고',
    profileImage: '/avatar2.png',
    follow: true,
    title: '오늘의 주제: "프론트엔드 언어의 역사"',
    content: `너 진짜 프론트엔드 할 거야? 그게 진짜 까다롭구 어려워 생각보다 아니 그니까 일단 눈에 보이는 거라서 어쩌면 더 어려울 수 있다니까는? 눈에 보이기만 하면 뭐하냐고 예뻐보여야하는데... 이런 거면 디자이너랑 뭐가 다른데 진짜 돈 더 줘라 돈 더 줘! 프론트 연봉 올려줘라 줘!!!!`,
    date: '2025.06.13',
    time: '3시간 전',
    likes: 258,
    comments: 18,
  },
  {
    id: 11,
    author: '개발자작냐고',
    profileImage: '/avatar2.png',
    follow: false,
    title: '오늘의 주제: "프론트엔드 언어의 역사"',
    content: `너 진짜 프론트엔드 할 거야? 그게 진짜 까다롭구 어려워 생각보다 아니 그니까 일단 눈에 보이는 거라서 어쩌면 더 어려울 수 있다니까는? 눈에 보이기만 하면 뭐하냐고 예뻐보여야하는데... 이런 거면 디자이너랑 뭐가 다른데 진짜 돈 더 줘라 돈 더 줘! 프론트 연봉 올려줘라 줘!!!!`,
    date: '2025.06.13',
    time: '3시간 전',
    likes: 258,
    comments: 18,
  },
];
