name: Deploy to EC2 with Docker(develop)

on:
  push:
    branches:
      - feature/14

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # GitHub 레포지토리 코드 체크아웃
      - name: Checkout source code
        uses: actions/checkout@v4

      #  DockerHub 로그인
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Docker 이미지 빌드 및 DockerHub에 푸시
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fixlog-front:latest

      # EC2에 SSH 접속 후 이미지 pull + 컨테이너 재시작
      - name: SSH and deploy on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            docker stop fixlog-container || true
            docker rm fixlog-container || true

            docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/fixlog-front:latest || true

            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/fixlog-front:latest

            docker run -d -p 3001:3000 --name fixlog-container ${{ secrets.DOCKERHUB_USERNAME }}/fixlog-front:latest
