name: Deploy to EC2 (develop)

on:
  push:
    branches:
      - feature/14 # 브랜치 이름 수정 필요

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Copy files to EC2 and deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd ~/fixlog_front/fixlog_front  
            git fetch origin
            git checkout feature/14 || git checkout -b feature/14 origin/feature/14
            git pull origin feature/14
            yarn install --frozen-lockfile
            yarn build
            pm2 reload fixlog-dev || pm2 start yarn --name "fixlog-dev" -- start
